version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: remote_host=host.docker.internal

    ports:
      - "9003:9003"
    networks:
      - laravel

  #  node:
  #    image: node:16-alpine
  #    container_name: laravel_node
  #    working_dir: /var/www/html
  #    volumes:
  #      - ./www:/var/www/html
  #    command: npm install && npm run dev
  #    networks:
  #      - laravel


  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - /www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mariadb:10.11.6
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    networks:
      - laravel




networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
